### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [pedrozaalex/tiny_snails#11]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by pedrozaalex** [comment]
That's a very good point.
Thanks for the tip, I'll include a license asap!

**Comment by TechnologyClassroom** [comment]
GitHub sort of walks you through the steps once you get started.

1. In GitHub, start at the repository page.
1. Click on the `Add file` button and select `Create new file`.
1. In the `Name of your file...` text box, type in `LICENSE.md` and a new button will appear.
1. Click on the `Choose a license template` button.
1. Click on a license on the left and a brief summary will appear.
1. Fill out the copyright line text box if applicable with something like `Copyright 2018-2021 John Doe`.
1. Click on the `Review and Submit` button.
1. Beneath `Commit new file` enter a commit description.  I like to use the precise SPDX short identifier for the commit such as `GPL-3.0-or-later` or `AGPL-3.0-or-later`.
1. Click on the `Commit directly to the x branch.` radio button.
1. Click on the `Commit new file` button.

**Comment by pedrozaalex** [comment]
Thanks for the tip! I did not know GitHub helped you with that.

I ended up going with MIT for simplicity!
