### ISSUE TITLE
Store dark mode settings locally

### ISSUE THREAD

**Issue by pedrozaalex** [pedrozaalex/tiny_snails#5]

**Comment by BAM5** [comment]
Also you can look into https://stackoverflow.com/questions/56393880/how-do-i-detect-dark-mode-using-javascript to detect OS theme to use as default.

**Comment by ElijahPepe** [comment]
@BAM5 `prefers-color-scheme: dark` is redundant in Chakra UI Vue; IIRC the color mode `system` works fine as to detect the OS theme.

**Comment by pedrozaalex** [comment]
Issue fixed by #12, thanks a lot @ElijahPepe and @BAM5!
