### ISSUE TITLE
Better footer

### ISSUE THREAD

**Issue by pedrozaalex** [pedrozaalex/tiny_snails#6]
Footer is too generic right now, with the "made with love" yadda yadda.

**Comment by ElijahPepe** [comment]
What kind of things could go into the footer?

**Comment by pedrozaalex** [comment]
![image](https://user-images.githubusercontent.com/19731594/155230874-88272df5-cf59-4c3e-8ea9-f59ebfa1c263.png)

The footer was bothering me as a whole, so I removed it altogether lol 

But I loved the GitHub icon idea, so I put on the header, next to the leaderboard and stuff.

What do you think? If you approve it we can merge #17 already.

In the future I'm thinking of putting some stuff like "powered by Vue, Nuxt, Fauna etc.", it's still cheesy but at least it's less cheesy than that "made with :heart:" thing that everyone does lmao

**Comment by ElijahPepe** [comment]
I like that idea, yeah.
